name: flutter_dynamic_color_sample
description: "A `Dynamic Color` sample"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter

dev_dependencies:
  custom_lint: ^0.7.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  nilts: ^0.17.0
  pedantic_mono: ^1.29.0

flutter:
  uses-material-design: true
